ARG BASE_IMAGE=cpu_base

FROM ${BASE_IMAGE} 

RUN sed -i "s/;http_port =.*/http_port = 8081/g" /etc/grafana/grafana.ini

# pip3 dep
# RUN pip3 install --no-cache-dir --upgrade \
#     opencv-python==4.1.0.25 \
#     gevent==20.9.0 \
#     --index-url=https://mirrors.tencent.com/repository/pypi/tencent_pypi/simple \
#     --extra-index-url=https://mirrors.tencent.com/pypi/simple

# hok_env
RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage && \
    chmod u+x nvim.appimage && \
    ./nvim.appimage --appimage-extract && \
    cp -r ./squashfs-root/usr/ / && \
    rm -r squashfs-root nvim.appimage && \
    ln -sf /usr/bin/nvim /usr/bin/vim

COPY hok_env /hok_env
RUN pip3 install --no-cache-dir -e /hok_env

# rl_framework
COPY ./rl_framework/ /rl_framework/

RUN cd /rl_framework/common && python3 setup.py bdist_wheel && pip3 install --no-cache-dir dist/*.whl && python3 setup.py clean --all && rm -rf dist/
RUN cd /rl_framework/learner && python3 setup.py bdist_wheel && pip3 install --no-cache-dir dist/*.whl && python3 setup.py clean --all && rm -rf dist/
RUN cd /rl_framework/mem_pool && python3 setup.py bdist_wheel && pip3 install --no-cache-dir dist/*.whl && python3 setup.py clean --all && rm -rf dist/
RUN cd /rl_framework/model_pool && python3 setup.py bdist_wheel && pip3 install --no-cache-dir dist/*.whl && python3 setup.py clean --all && rm -rf dist/
RUN cd /rl_framework/predictor && python3 setup.py bdist_wheel && pip3 install --no-cache-dir dist/*.whl && python3 setup.py clean --all && rm -rf dist/

RUN pip3 install --no-cache-dir --upgrade build && \
    cd /rl_framework/monitor && python3 -m build && \
    pip3 install --no-cache-dir dist/*.whl && rm -rf dist/

# training code
COPY ./aiarena/1v1/actor /aiarena/code/actor
COPY ./aiarena/1v1/learner /aiarena/code/learner
COPY ./aiarena/1v1/common /aiarena/code/common
COPY ./aiarena/remote-gc-server /aiarena/remote-gc-server
COPY ./aiarena/battle /aiarena/battle
COPY ./aiarena/scripts /aiarena/scripts

# monitor config
COPY ./aiarena/1v1/common/monitor/dashboard/*.json /var/lib/grafana/dashboards/
COPY ./aiarena/1v1/common/monitor/config/datasource.yaml /etc/grafana/provisioning/datasources/
COPY ./aiarena/1v1/common/monitor/config/dashboard.yaml /etc/grafana/provisioning/dashboards/

WORKDIR /

ENV GAMECORE_SERVER_BIND_ADDR=:23432
ENV GAMECORE_SERVER_ADDR="127.0.0.1:23432"
