ARG BASE_IMAGE=cpu_base

FROM ${BASE_IMAGE} as dev_base

RUN wget https://github.com/prometheus/influxdb_exporter/releases/download/v0.10.0/influxdb_exporter-0.10.0.linux-amd64.tar.gz \
    && tar -xf influxdb_exporter-0.10.0.linux-amd64.tar.gz \
    && cp influxdb_exporter-0.10.0.linux-amd64/influxdb_exporter /usr/bin/ \
    && rm -rf influxdb_exporter-0.10.0.linux-amd64*

RUN sed -i "s/;http_port =.*/http_port = 8081/g" /etc/grafana/grafana.ini

# TODO hongyangqin move to base image
RUN apt update && \
    apt install -y lrzsz && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir absl-py

# rl_framework
COPY ./rl_framework/ /rl_framework/

RUN cd /rl_framework/common && python3 setup.py bdist_wheel && pip3 install --no-cache-dir dist/*.whl && python3 setup.py clean --all && rm -rf dist/
RUN cd /rl_framework/learner && python3 setup.py bdist_wheel && pip3 install --no-cache-dir dist/*.whl && python3 setup.py clean --all && rm -rf dist/
RUN cd /rl_framework/mem_pool && python3 setup.py bdist_wheel && pip3 install --no-cache-dir dist/*.whl && python3 setup.py clean --all && rm -rf dist/
RUN cd /rl_framework/model_pool && python3 setup.py bdist_wheel && pip3 install --no-cache-dir dist/*.whl && python3 setup.py clean --all && rm -rf dist/
RUN cd /rl_framework/predictor && python3 setup.py bdist_wheel && pip3 install --no-cache-dir dist/*.whl && python3 setup.py clean --all && rm -rf dist/

RUN pip3 install --no-cache-dir --upgrade build && \
    cd /rl_framework/monitor && python3 -m build && \
    pip3 install --no-cache-dir dist/*.whl && rm -rf dist/

# hok_env
COPY hok_env /hok_env
RUN pip3 install --no-cache-dir -e /hok_env

# training code
COPY ./aiarena/remote-gc-server /rl_framework/remote-gc-server
COPY ./aiarena/battle /aiarena/battle
COPY ./aiarena/process /aiarena/process
COPY ./aiarena/__init__.py /aiarena/
COPY ./aiarena/scripts /aiarena/scripts
COPY ./aiarena/grafana/etc /etc/grafana
COPY ./aiarena/grafana/dashboards /var/lib/grafana/dashboards

WORKDIR /

ENV GAMECORE_SERVER_BIND_ADDR=:23432
ENV GAMECORE_SERVER_ADDR="127.0.0.1:23432"

# runtime /aiarena/code 3v3 dir
FROM dev_base as code3v3
COPY ./aiarena/3v3/actor /aiarena/code/actor
COPY ./aiarena/3v3/learner /aiarena/code/learner

# runtime /aiarena/code 1v1 dir
FROM dev_base as code1v1
COPY ./aiarena/1v1/actor /aiarena/code/actor
COPY ./aiarena/1v1/learner /aiarena/code/learner
COPY ./aiarena/1v1/common /aiarena/code/common

FROM dev_base as battle
COPY ./aiarena/1v1/actor /aiarena/1v1/actor
COPY ./aiarena/1v1/learner /aiarena/1v1/learner
COPY ./aiarena/1v1/common /aiarena/1v1/common
COPY ./aiarena/3v3/actor /aiarena/3v3/actor
COPY ./aiarena/3v3/learner /aiarena/3v3/learner
