name: Docker Image CI
on:
  push:
    tags:
      - 'base_v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            tencentailab/hok_env
          # generate Docker tags based on the following events/attributes
          flavor: |
            prefix=base_
            latest=false
          tags: |
            type=sha,prefix=base_
            type=raw,value={{tag}},prefix=
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: dockerfile.base
          cache-from: type=registry,ref=tencentailab/hok_env:base_buildcache
          cache-to: type=registry,ref=tencentailab/hok_env:base_buildcache,mode=max
