name: Docker Image CI
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            tencentailab/hok_env
          # generate Docker tags based on the following events/attributes
          flavor: |
            prefix=baseline_1v1_dev_
          tags: |
            type=semver,pattern={{raw}}
            type=sha,prefix=baseline_1v1_dev_
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: dockerfile.dev
          cache-from: type=registry,ref=tencentailab/hok_env:buildcache
          cache-to: type=registry,ref=tencentailab/hok_env:buildcache,mode=max
